### PR TITLE
Add CyberTech Rome

### PR DESCRIPTION
**Pull request by gmellini**
## Purpose

Added CyberTech Rome  (26-27/09/2018)

## Sources

https://italy.cybertechconference.com/it

### CODE REVIEW

**Comment by evilsocket** [comment]
cyber-tech -> cybertech

**Comment by evilsocket** [comment]
also there's no editions folder

**Comment by gmellini** [comment]
ok @evilsocket sorry for the wrong PR.
I think that is better to close the issue and I make a new one with all the missing info.
Ok for you?

**Comment by gmellini** [comment]
closing, preparing a new PR

**Pull request closed without merging**
