### PR TITLE
Adding Internet Freedom Festival

### PR DESCRIPTION
**Pull request by ORARiccardo**
## Purpose

Adding Internet Freedom Festival and the new category Internet Community, related to conferences organized following a community-driven approach and focused on internet community issues at large.

## Sources

https://internetfreedomfestival.org/
https://www.internetfreedomfestival.org/wiki/index.php/Code_of_Conduct

### CODE REVIEW

**Comment by evilsocket** [comment]
build failing, please fix :)

**Comment by evilsocket** [comment]
category file does not exist + other errors, make sure your commits pass the build before sending the PR please

**Comment by ORARiccardo** [comment]
Sorry, I'm probably making the mistake of adding the new category and the event that falls into that category at the same time. Should I split the two PR? (And correct the other errors too)

**Comment by evilsocket** [comment]
No need to split, just send me one PR which passes the tests. Just see how other events and categories are implemented as a reference :)

**Pull request closed without merging**
