### PR TITLE
added MERGE-it conference

### PR DESCRIPTION
**Pull request by Germano0**
added MERGE-it conference

### CODE REVIEW

**Comment by evilsocket** [comment]
It does not merge.

**Comment by evilsocket** [comment]
@Germano0 fix the json file please, there are two objects ....

**Comment by evilsocket** [comment]
I'll do it.

**Comment by Germano0** [comment]
I added two objects since the same event will take place in two different places and I did not know how to write it into JSON

**Comment by evilsocket** [comment]
This is not how json works, please make sure you submit valid files.

**Pull request merged**
