### PR TITLE
Swiss Cyber Storm 2018

### PR DESCRIPTION
**Pull request by dune73**
New edition. That's all.

### CODE REVIEW

**Comment by evilsocket** [comment]
nope, missing event file, check other events and fix

**Comment by dune73** [comment]
Why is that? The event file is already there. This is just new edition.

**Comment by evilsocket** [comment]
name is wrong, there's already one like that, they have to be unique

**Comment by dune73** [comment]
I take it that would be the title. Let's see if Travis likes that.

**Comment by dune73** [comment]
Thank you.

**Pull request merged**
